clc;
clear all;
close all;
format longg

tensor_2D = [2.0 0.0; ...
             0.0 3.0];
tensor_3D = [2.0 0.0 0; ...
             0.0 3.0 0.0; ...
             0.0 0.0 7.0];

% rotation angles (degree, radian)
ra  = [30.0, 40.0, 10.0];
rar = ra / 180.0 * pi;

% rotation matrices
rm_2D   = [cos(rar(1)), -sin(rar(1)); ...
           sin(rar(1)),  cos(rar(1))];
rm_3D   = [cos(rar(1))*cos(rar(2))*cos(rar(3))-sin(rar(1))*sin(rar(3)), ...
           -cos(rar(1))*cos(rar(2))*sin(rar(3))-sin(rar(1))*cos(rar(3)), ...
           cos(rar(1))*sin(rar(2)); ...
           sin(rar(1))*cos(rar(2))*cos(rar(3))+cos(rar(1))*sin(rar(3)), ...
           -sin(rar(1))*cos(rar(2))*sin(rar(3))+cos(rar(1))*cos(rar(3)), ...
           sin(rar(1))*sin(rar(2)); ...
           -sin(rar(2))*cos(rar(3)), ...
           sin(rar(2))*sin(rar(3)), ...
           cos(rar(2))];

% conductivity tensor
rot_2D = rm_2D * tensor_2D * rm_2D'
rot_3D = rm_3D * tensor_3D * rm_3D'

rot_2D(:)'
rot_3D(:)'
